on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *" # every hour

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "cozy-ci"
          image-tags: "!main"
          cut-off: 1w
          keep-n-most-recent: 3
          dry-run: true
